version: '3'

services:
  app:
    image: '${DOCKER_REGISTRY}/${ENV}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}'
    restart: always
    environment:
      TZ: ${TZ}
      ENV: ${ENV}
      APP_PORT: ${APP_PORT}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
      LOGGER_FILE: ${LOGGER_FILE}
    ports:
      - ${DOCKER_NODEJS_PORT}:${APP_PORT}
    extra_hosts:
      - "host.internal:host-gateway"
    command: npm run serve
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"