version: '3'

services:
  app:
    image: '${DOCKER_REGISTRY}/${ENV}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_VERSION}'
    restart: always
    environment:
      TZ: ${TZ}
    ports:
      - ${DOCKER_NODEJS_PORT}:${APP_PORT}
      - 9229:9229
    volumes:
      - .:/app
    extra_hosts:
      - "host.internal:host-gateway"
    command: npm run debug
